import { Level } from './types';

export const starterLevels: Level[] = [
  {
    id: 1,
    language: 'en',
    letters: ['S', 'T', 'A', 'R'],
    mainWords: [
      { word: 'STAR', row: 0, col: 0, direction: 'across' },
      { word: 'ART', row: 1, col: 1, direction: 'across' },
      { word: 'RAT', row: 2, col: 0, direction: 'across' },
    ],
    bonusWords: ['TAR', 'SAT'],
    difficulty: 'easy',
    themeId: 'dawn-garden',
    rewardCoins: 15,
  },
  {
    id: 2,
    language: 'en',
    letters: ['P', 'L', 'A', 'N', 'E'],
    mainWords: [
      { word: 'PLANE', row: 0, col: 0, direction: 'across' },
      { word: 'LANE', row: 1, col: 1, direction: 'across' },
      { word: 'PAN', row: 2, col: 0, direction: 'across' },
    ],
    bonusWords: ['PLAN', 'LEAN', 'PALE', 'LEAP'],
    difficulty: 'easy',
    themeId: 'dawn-garden',
    rewardCoins: 18,
  },
  {
    id: 3,
    language: 'en',
    letters: ['S', 'T', 'O', 'N', 'E'],
    mainWords: [
      { word: 'STONE', row: 0, col: 0, direction: 'across' },
      { word: 'TONE', row: 1, col: 1, direction: 'across' },
      { word: 'NOTE', row: 2, col: 0, direction: 'across' },
    ],
    bonusWords: ['ONES', 'TOES', 'SENT', 'NEST'],
    difficulty: 'normal',
    themeId: 'dawn-garden',
    rewardCoins: 22,
  },
  {
    id: 1,
    language: 'es',
    letters: ['S', 'O', 'L', 'A'],
    mainWords: [
      { word: 'SOLA', row: 0, col: 0, direction: 'across' },
      { word: 'SOL', row: 1, col: 0, direction: 'across' },
      { word: 'OLA', row: 2, col: 1, direction: 'across' },
    ],
    bonusWords: ['LAS', 'SAL'],
    difficulty: 'easy',
    themeId: 'sunny-coast',
    rewardCoins: 15,
  },
  {
    id: 2,
    language: 'es',
    letters: ['M', 'A', 'R', 'E', 'S'],
    mainWords: [
      { word: 'MARES', row: 0, col: 0, direction: 'across' },
      { word: 'MAR', row: 1, col: 0, direction: 'across' },
      { word: 'SER', row: 2, col: 2, direction: 'across' },
    ],
    bonusWords: ['MAS'],
    difficulty: 'easy',
    themeId: 'sunny-coast',
    rewardCoins: 18,
  },
  {
    id: 3,
    language: 'es',
    letters: ['C', 'A', 'M', 'I', 'N', 'O'],
    mainWords: [
      { word: 'CAMINO', row: 0, col: 0, direction: 'across' },
      { word: 'MANO', row: 1, col: 1, direction: 'across' },
      { word: 'CIMA', row: 2, col: 0, direction: 'across' },
    ],
    bonusWords: ['AMO', 'COMA'],
    difficulty: 'normal',
    themeId: 'sunny-coast',
    rewardCoins: 22,
  },
  {
    id: 1,
    language: 'ru',
    letters: ['Л', 'Е', 'С', 'А'],
    mainWords: [
      { word: 'ЛЕСА', row: 0, col: 0, direction: 'across' },
      { word: 'ЛЕС', row: 1, col: 0, direction: 'across' },
      { word: 'ЕЛА', row: 2, col: 1, direction: 'across' },
    ],
    bonusWords: ['СЕЛ'],
    difficulty: 'easy',
    themeId: 'mystic-forest',
    rewardCoins: 15,
  },
  {
    id: 2,
    language: 'ru',
    letters: ['М', 'О', 'Р', 'Е'],
    mainWords: [
      { word: 'МОРЕ', row: 0, col: 0, direction: 'across' },
      { word: 'МОР', row: 1, col: 0, direction: 'across' },
      { word: 'РОМ', row: 2, col: 1, direction: 'across' },
    ],
    bonusWords: ['МЕР'],
    difficulty: 'easy',
    themeId: 'crystal-lake',
    rewardCoins: 18,
  },
  {
    id: 3,
    language: 'ru',
    letters: ['К', 'А', 'Р', 'Т', 'А'],
    mainWords: [
      { word: 'КАРТА', row: 0, col: 0, direction: 'across' },
      { word: 'КАРА', row: 1, col: 0, direction: 'across' },
      { word: 'АРКА', row: 2, col: 1, direction: 'across' },
    ],
    bonusWords: ['АКТ'],
    difficulty: 'normal',
    themeId: 'mystic-forest',
    rewardCoins: 22,
  },
  {
    id: 1,
    language: 'tr',
    letters: ['K', 'A', 'L', 'E'],
    mainWords: [
      { word: 'KALE', row: 0, col: 0, direction: 'across' },
      { word: 'KAL', row: 1, col: 0, direction: 'across' },
      { word: 'EL', row: 2, col: 2, direction: 'across' },
    ],
    bonusWords: ['AL'],
    difficulty: 'easy',
    themeId: 'ancient-city',
    rewardCoins: 15,
  },
  {
    id: 2,
    language: 'tr',
    letters: ['D', 'E', 'N', 'İ', 'Z'],
    mainWords: [
      { word: 'DENİZ', row: 0, col: 0, direction: 'across' },
      { word: 'DEN', row: 1, col: 0, direction: 'across' },
      { word: 'İZ', row: 2, col: 3, direction: 'across' },
    ],
    bonusWords: ['DİN'],
    difficulty: 'easy',
    themeId: 'crystal-lake',
    rewardCoins: 18,
  },
  {
    id: 3,
    language: 'tr',
    letters: ['K', 'İ', 'T', 'A', 'P'],
    mainWords: [
      { word: 'KİTAP', row: 0, col: 0, direction: 'across' },
      { word: 'KİT', row: 1, col: 0, direction: 'across' },
      { word: 'TAP', row: 2, col: 2, direction: 'across' },
    ],
    bonusWords: ['KAT', 'KAP', 'İP'],
    difficulty: 'normal',
    themeId: 'ancient-city',
    rewardCoins: 22,
  },
];
