import { LanguageCode } from '../i18n/languages';

export const realNounPools: Record<LanguageCode, string[]> = {
  en: ['ART','STAR','RAT','TAR','ROAD','STONE','TREE','WATER','HOUSE','BRIDGE','FOREST','MARKET','RIVER','MUSIC','GARDEN','CLOUD','HEART','WORLD','MOUNTAIN','FLOWER','ISLAND','OCEAN','BREAD','TABLE','CHAIR','SCHOOL','BOOK','PAPER','CITY','VILLAGE','FAMILY','FRIEND','HORSE','BIRD','FIELD','CLOCK','TRAIN','PLANE','BEACH','VALLEY','LAKE','HILL','MILL','FARM','BARN','DOOR','WALL','ROOM','ROOF','FLOOR','KEY','KING','QUEEN','CROWN','RING','COIN','SILVER','GOLD','EARTH','NIGHT','MORNING','SISTER','BROTHER','MOTHER','FATHER','CHILD','APPLE','PEAR','GRAPE','LEMON','PEACH','BERRY','CHEESE','HONEY','SUGAR','SALT','FISH','SHEEP','GOAT','DOG','CAT','MOUSE','LION','TIGER','BEAR','WOLF','FOX','DEER','EAGLE','CROW','ROSE','GRASS','LEAF','ROOT','SEED','SUN','MOON','RAIN','SNOW','WIND','FIRE','SAND','SEA','SHIP','BOAT'],
  es: ['SOL','SAL','ALA','CASA','RIO','MAR','PAN','FLOR','LUZ','TREN','PIEDRA','MESA','SILLA','LIBRO','PAPEL','CIUDAD','PUEBLO','FAMILIA','AMIGO','CABALLO','PAJARO','CAMPO','RELOJ','PLAYA','LLUVIA','NIEVE','VIENTO','VOZ','ORO','PLATA','TIERRA','NOCHE','DIA','LAGO','MONTE','COLINA','GRANJA','PUERTA','PARED','CUARTO','TECHO','SUELO','LLAVE','REY','REINA','CORONA','ANILLO','MONEDA','MUNDO','MADRE','PADRE','HERMANO','HERMANA','NIÑO','MANZANA','PERA','UVA','LIMON','DURAZNO','QUESO','MIEL','AZUCAR','PESCADO','OVEJA','CABRA','PERRO','GATO','RATON','LEON','TIGRE','OSO','LOBO','ZORRO','CIERVO','AGUILA','CUERVO','ROSA','HIERBA','HOJA','RAIZ','SEMILLA','LUNA','FUEGO','ARENA','BARCO','BOTE'],
  ru: ['ДОМ','КОТ','ЛЕС','САД','МИР','РЕКА','ВОДА','ОКНО','СВЕТ','ЛУНА','СНЕГ','ГОРОД','МОСТ','КАМЕНЬ','ДЕРЕВО','ПОЛЕ','КНИГА','ШКОЛА','СТОЛ','СТУЛ','ДРУГ','СЕМЬЯ','ПЕСНЯ','МОРЕ','ОСТРОВ','ГОРА','ЦВЕТОК','ОБЛАКО','ДОРОГА','ХЛЕБ','ДЕНЬ','НОЧЬ','ОЗЕРО','ХОЛМ','ФЕРМА','ДВЕРЬ','СТЕНА','КОМНАТА','КРЫША','ПОЛ','КЛЮЧ','КОРОЛЬ','КОРОНА','КОЛЬЦО','МОНЕТА','ЗОЛОТО','СЕРЕБРО','ЗЕМЛЯ','УТРО','МАТЬ','ОТЕЦ','БРАТ','СЕСТРА','РЕБЕНОК','ЯБЛОКО','ГРУША','ВИНОГРАД','ЛИМОН','СЫР','МЕД','САХАР','СОЛЬ','РЫБА','ОВЦА','КОЗА','СОБАКА','МЫШЬ','ЛЕВ','ТИГР','МЕДВЕДЬ','ВОЛК','ЛИСА','ОЛЕНЬ','ОРЕЛ','ВОРОН','РОЗА','ТРАВА','ЛИСТ','КОРЕНЬ','СЕМЯ','СОЛНЦЕ','ДОЖДЬ','ВЕТЕР','ОГОНЬ','ПЕСОК','КОРАБЛЬ','ЛОДКА'],
  tr: ['EV','SU','EL','İL','DİL','AT','AY','YOL','TAŞ','KAR','BAĞ','BAL','DAL','GÜL','GÖL','KUŞ','OKUL','KİTAP','MASA','ŞEHİR','KÖY','AİLE','DOST','YAĞMUR','RÜZGAR','TOPRAK','GECE','SABAH','ORMAN','KÖPRÜ','GÜN','GÜNEŞ','DENİZ','ADA','DAĞ','NEHİR','BAHÇE','ÇİÇEK','BULUT','KALP','DÜNYA','MÜZİK','PENCERE','KAPI','DUVAR','ODA','ÇATI','ANAHTAR','KRAL','TAÇ','YÜZÜK','PARA','ALTIN','GÜMÜŞ','ANNE','BABA','KARDEŞ','ÇOCUK','ELMA','ARMUT','ÜZÜM','LİMON','PEYNİR','BALIK','KOYUN','KEÇİ','KÖPEK','KEDİ','FARE','ASLAN','KAPLAN','AYI','KURT','TİLKİ','GEYİK','KARTAL','KARGA','YAPRAK','KÖK','TOHUM','ATEŞ','KUM','GEMİ','TEKNE'],
  de: ['HAUS','SEE','BAUM','WEG','STEIN','BLUME','GARTEN','BRÜCKE','WALD','WOLKE','HERZ','WELT','MUSIK','FENSTER','BURG','INSEL','BROT','TISCH','STUHL','SCHULE','BUCH','PAPIER','STADT','DORF','FAMILIE','FREUND','PFERD','VOGEL','FELD','UHR','TAG','NACHT','MOND','SONNE','REGEN','SCHNEE','WIND','FEUER','SAND','MEER','FLUSS','BERG','TAL','BAUERNHOF','TÜR','WAND','ZIMMER','DACH','BODEN','SCHLÜSSEL','KÖNIG','KRONE','RING','MÜNZE','GOLD','SILBER','ERDE','MUTTER','VATER','BRUDER','SCHWESTER','KIND','APFEL','BIRNE','TRAUBE','ZITRONE','KÄSE','HONIG','ZUCKER','SALZ','FISCH','SCHAF','ZIEGE','HUND','KATZE','MAUS','LÖWE','TIGER','BÄR','WOLF','FUCHS','HIRSCH','ADLER','KRÄHE','ROSE','GRAS','BLATT','WURZEL','SAMEN','SCHIFF','BOOT'],
  pt: ['SOL','CASA','RIO','MAR','FLOR','LUZ','TREM','PEDRA','MESA','CADEIRA','LIVRO','PAPEL','CIDADE','ALDEIA','FAMILIA','AMIGO','CAVALO','CAMPO','PRAIA','CHUVA','NEVE','VENTO','VOZ','OURO','PRATA','TERRA','NOITE','MANHA','PONTE','JARDIM','DIA','LUA','FOGO','AREIA','LAGO','MONTE','COLINA','FAZENDA','PORTA','PAREDE','QUARTO','TELHADO','CHAO','CHAVE','REI','RAINHA','COROA','ANEL','MOEDA','MUNDO','MAE','PAI','IRMAO','IRMA','CRIANCA','MACA','PERA','UVA','LIMAO','QUEIJO','MEL','ACUCAR','SAL','PEIXE','OVELHA','CABRA','CAO','GATO','RATO','LEAO','TIGRE','URSO','LOBO','RAPOSA','CERVO','AGUIA','CORVO','ROSA','ERVA','FOLHA','RAIZ','SEMENTE','NAVIO','BARCO'],
  it: ['SOLE','CASA','FIUME','MARE','PANE','FIORE','LUCE','TRENO','PIETRA','TAVOLO','SEDIA','LIBRO','CARTA','CITTA','PAESE','FAMIGLIA','AMICO','CAVALLO','CAMPO','SPIAGGIA','PIOGGIA','NEVE','VENTO','VOCE','ORO','ARGENTO','TERRA','NOTTE','PONTE','GIARDINO','GIORNO','LUNA','FUOCO','SABBIA','LAGO','MONTE','COLLINA','FATTORIA','PORTA','PARETE','STANZA','TETTO','PAVIMENTO','CHIAVE','RE','REGINA','CORONA','ANELLO','MONETA','MONDO','MADRE','PADRE','FRATELLO','SORELLA','BAMBINO','MELA','PERA','UVA','LIMONE','FORMAGGIO','MIELE','ZUCCHERO','SALE','PESCE','PECORA','CAPRA','CANE','GATTO','TOPO','LEONE','TIGRE','ORSO','LUPO','VOLPE','CERVO','AQUILA','CORVO','ROSA','ERBA','FOGLIA','RADICE','SEME','NAVE','BARCA'],
  fr: ['MAISON','LUNE','EAU','FEU','ARBRE','RIVIERE','PIERRE','FLEUR','JARDIN','PONT','FORET','NUAGE','COEUR','MONDE','MUSIQUE','FENETRE','CHATEAU','PAIN','TABLE','CHAISE','ECOLE','LIVRE','PAPIER','VILLE','VILLAGE','FAMILLE','AMI','CHEVAL','OISEAU','CHAMP','JOUR','NUIT','SOLEIL','PLUIE','NEIGE','VENT','SABLE','MER','LAC','COLLINE','FERME','PORTE','MUR','CHAMBRE','TOIT','SOL','CLE','ROI','REINE','COURONNE','BAGUE','PIECE','OR','ARGENT','TERRE','MERE','PERE','FRERE','SOEUR','ENFANT','POMME','POIRE','RAISIN','CITRON','FROMAGE','MIEL','SUCRE','SEL','POISSON','MOUTON','CHEVRE','CHIEN','CHAT','SOURIS','LION','TIGRE','OURS','LOUP','RENARD','CERF','AIGLE','CORBEAU','ROSE','HERBE','FEUILLE','RACINE','GRAINE','NAVIRE','BATEAU'],
  az: ['EV','SU','OD','ƏL','İL','DİL','AT','AY','YOL','DAŞ','QAR','BAĞ','BAL','DAL','GÜL','GÖL','QUŞ','KİTAB','MASA','ŞƏHƏR','KƏND','AİLƏ','DOST','YAĞIŞ','KÜLƏK','TORPAQ','GECƏ','SƏHƏR','MEŞƏ','KÖRPÜ','GÜN','GÜNƏŞ','DƏNİZ','ADA','DAĞ','ÇAY','BAĞÇA','ÇİÇƏK','BULUD','ÜRƏK','DÜNYA','MUSİQİ','PƏNCƏRƏ','QAPI','DİVAR','OTAQ','DAM','DÖŞƏMƏ','AÇAR','KRAL','TAC','ÜZÜK','PUL','QIZIL','GÜMÜŞ','ANA','ATA','QARDAŞ','BACİ','UŞAQ','ALMA','ARMUD','ÜZÜM','LİMON','PENDİR','BALIQ','QOYUN','KEÇİ','İT','PİŞİK','SİÇAN','ASLAN','PƏLƏNG','AYI','CANAVAR','TÜLKÜ','MARAL','QARTAL','QARĞA','YARPAQ','KÖK','TOXUM','QUM','GƏMİ','QAYIQ'],
  hi: ['घर','जल','आग','फल','फूल','दूध','रोटी','नदी','रात','दिन','खेत','हाथ','पैर','शहर','गांव','दोस्त','किताब','कागज','बाग','पुल','जंगल','बादल','दिल','दुनिया','संगीत','किला','मेज','कुर्सी','घड़ी','कहानी','पेड़','रास्ता','पत्थर','समुद्र','पहाड़','दरवाजा','दीवार','कमरा','छत','फर्श','चाबी','राजा','रानी','मुकुट','अंगूठी','सिक्का','सोना','चांदी','धरती','सुबह','मां','पिता','भाई','बहन','बच्चा','सेब','नाशपाती','अंगूर','नींबू','पनीर','शहद','चीनी','नमक','मछली','भेड़','बकरी','कुत्ता','बिल्ली','चूहा','शेर','बाघ','भालू','भेड़िया','लोमड़ी','हिरण','चील','कौआ','गुलाब','घास','पत्ता','जड़','बीज','नाव'],
  zh: ['家','水','火','树','路','石','花','园','桥','云','心','书','纸','马','鸟','雨','雪','风','金','银','山','海','田','城','村','门','车','船','月','日','夜','湖','谷','房','墙','屋','钥','王','冠','环','钱','地','母','父','兄','姐','孩','果','梨','葡','瓜','鱼','羊','狗','猫','鼠','狮','虎','熊','狼','狐','鹿','鹰','鸦','草','叶','根','种','沙','岛','河','星','光','面','椅','桌','校','友'],
  ja: ['家','水','火','木','道','石','花','庭','橋','森','雲','心','本','紙','馬','鳥','雨','雪','風','金','銀','山','海','町','村','門','車','船','月','日','夜','湖','谷','部屋','壁','屋根','鍵','王','冠','輪','金貨','地','母','父','兄','姉','子','林檎','梨','葡萄','魚','羊','犬','猫','鼠','獅子','虎','熊','狼','狐','鹿','鷲','烏','草','葉','根','種','砂','島','川','星','光','机','学校','友達'],
  ko: ['집','물','불','나무','길','돌','꽃','정원','다리','숲','구름','마음','책','종이','말','새','비','눈','바람','금','은','산','바다','도시','마을','문','차','배','달','해','밤','호수','골짜기','방','벽','지붕','바닥','열쇠','왕','왕관','반지','동전','땅','아침','어머니','아버지','형제','자매','아이','사과','배','포도','레몬','치즈','꿀','설탕','소금','물고기','양','염소','개','고양이','쥐','사자','호랑이','곰','늑대','여우','사슴','독수리','까마귀','장미','풀','잎','뿌리','씨앗','모래','섬','강','별','빛'],
};